# fly.toml app configuration file generated for intro-to-docker on 2024-03-05T06:47:53-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "intro-to-docker"
primary_region = "ord"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
